language: generic
sudo: required
services:
  - docker

before_install:
  - cd simple_CICD/frontend
  - docker build -t alexkovalenko/simpleweb -f Dockerfile.dev .
 
script:
  - docker run -e CI=true alexkovalenko/simpleweb npm run test
