language: generic
sudo: required
services:
  - docker

before_install:
  - cd simple_CICD/frontend
  - docker build -t alexkovalenko/simpleweb -f Dockerfile.dev .
 
script:
  - docker run -e CI=true alexkovalenko/simpleweb npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "simpleweb"
  env: "Simpleweb-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-395343194367"
  bucket_path: "simpleweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
