version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"

  webapp:
    build: ./web
    ports:
      - "8081:8081"
    depends_on:
      - redis-server
    restart: unless-stopped 
